-- Create time_slot_details table if it doesn't exist
CREATE TABLE IF NOT EXISTS time_slot_details (
  SLOT_ID INT AUTO_INCREMENT PRIMARY KEY,
  EXPERT_ID INT NOT NULL,
  AVAILABLE_DATE DATE,
  AVAILABLE_TIME TIME,
  SLOT_LABEL VARCHAR(255) DEFAULT '',
  IS_BOOKED TINYINT(1) DEFAULT 0,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (EXPERT_ID) REFERENCES profile_details(ID) ON DELETE CASCADE
);

-- Show table structure
DESCRIBE time_slot_details; 